// ─────────────────────────────────────────────
//  FILTER DIMENSIONS  (7 root axes)
// ─────────────────────────────────────────────
const DIMENSIONS = [
  {
    id: "domain",
    label: "Domain of Reality",
    icon: "◈",
    description: "Which layer of reality does the work interact with?",
    color: "#a78bfa",
    options: [
      { value: "physical",      label: "Physical World",             icon: "⚛",  sub: "Matter, Energy, Infrastructure, Manufacturing" },
      { value: "digital",       label: "Digital / Informational",    icon: "⟨⟩", sub: "Software, AI, Data, Networks, Cyber" },
      { value: "human_social",  label: "Human / Social World",       icon: "⬡",  sub: "Psychology, Education, Culture, Economics" },
      { value: "symbolic",      label: "Symbolic / Abstract",        icon: "∞",  sub: "Mathematics, Philosophy, Logic, Theory" },
      { value: "experiential",  label: "Experiential / Creative",    icon: "✦",  sub: "Art, Story, Music, Film, Games" },
    ],
  },
  {
    id: "target",
    label: "Target of Impact",
    icon: "◎",
    description: "What is the work trying to change?",
    color: "#60a5fa",
    options: [
      { value: "matter",        label: "Matter",         icon: "⬡" },
      { value: "life",          label: "Life",           icon: "⬢" },
      { value: "mind",          label: "Mind",           icon: "◉" },
      { value: "information",   label: "Information",    icon: "≋" },
      { value: "society",       label: "Society",        icon: "⬟" },
      { value: "civilization",  label: "Civilization",   icon: "◈" },
      { value: "consciousness", label: "Consciousness",  icon: "✿" },
    ],
  },
  {
    id: "creation",
    label: "Type of Creation",
    icon: "⬡",
    description: "What kind of output is produced?",
    color: "#f472b6",
    options: [
      { value: "knowledge",       label: "Knowledge",               icon: "◎" },
      { value: "technology",      label: "Technology",              icon: "⚙" },
      { value: "systems",         label: "Systems",                 icon: "⬡" },
      { value: "experiences",     label: "Experiences",             icon: "✦" },
      { value: "infrastructure",  label: "Infrastructure",          icon: "▣" },
      { value: "institutions",    label: "Institutions",            icon: "⬟" },
      { value: "stories_culture", label: "Stories / Culture",       icon: "◈" },
    ],
  },
  {
    id: "abstraction",
    label: "Level of Abstraction",
    icon: "▲",
    description: "Where on the thinker–builder–operator spectrum?",
    color: "#34d399",
    options: [
      { value: "pure_theory",    label: "Pure Theory",              icon: "∞" },
      { value: "conceptual",     label: "Conceptual Design",        icon: "◎" },
      { value: "engineering",    label: "Engineering / Impl.",       icon: "⚙" },
      { value: "operation",      label: "Operation / Execution",    icon: "▶" },
      { value: "maintenance",    label: "Maintenance",              icon: "⟳" },
    ],
  },
  {
    id: "scale",
    label: "Scale of Impact",
    icon: "◉",
    description: "What is the scope of the work?",
    color: "#fb923c",
    options: [
      { value: "personal",       label: "Personal",                 icon: "○" },
      { value: "local",          label: "Local",                    icon: "◔" },
      { value: "organizational", label: "Organizational",           icon: "◑" },
      { value: "national",       label: "National",                 icon: "◕" },
      { value: "global",         label: "Global",                   icon: "●" },
      { value: "planetary",      label: "Planetary",                icon: "◉" },
      { value: "cosmic",         label: "Cosmic",                   icon: "✦" },
    ],
  },
  {
    id: "time",
    label: "Time Horizon",
    icon: "◷",
    description: "What is the temporal orientation of the work?",
    color: "#e879f9",
    options: [
      { value: "immediate",       label: "Immediate (days)",         icon: "⚡" },
      { value: "short",           label: "Short-term (months)",      icon: "▷" },
      { value: "medium",          label: "Medium-term (years)",      icon: "▶" },
      { value: "long",            label: "Long-term (decades)",      icon: "⊳" },
      { value: "civilizational",  label: "Civilizational (centuries)", icon: "∞" },
    ],
  },
  {
    id: "mode",
    label: "Mode of Activity",
    icon: "⟳",
    description: "How is the work performed?",
    color: "#fbbf24",
    options: [
      { value: "discovery",      label: "Discovery",                icon: "◎" },
      { value: "creation_m",    label: "Creation",                 icon: "✦" },
      { value: "optimization",   label: "Optimization",             icon: "⚙" },
      { value: "coordination",   label: "Coordination",             icon: "⬡" },
      { value: "teaching",       label: "Teaching",                 icon: "▷" },
      { value: "healing",        label: "Healing",                  icon: "✿" },
      { value: "exploration",    label: "Exploration",              icon: "◈" },
    ],
  },
];

// ─────────────────────────────────────────────
//  WORK DOMAINS  (~150 entries)
// ─────────────────────────────────────────────
const DOMAINS = [
  // ── PHYSICAL WORLD ────────────────────────
  { id: 1,  name: "Materials Science",       layer: "Matter",         domain: ["physical"],       target: ["matter"],        creation: ["knowledge","technology"],   abstraction: ["engineering","pure_theory"],  scale: ["global"],         time: ["long"],            mode: ["discovery","creation_m"],  future: true,  emoji: "⬡", desc: "Discovering and engineering novel materials with extraordinary properties—superconductors, metamaterials, ultra-light composites." },
  { id: 2,  name: "Chemistry",               layer: "Matter",         domain: ["physical","symbolic"], target: ["matter"],   creation: ["knowledge","technology"],   abstraction: ["pure_theory","engineering"],  scale: ["global"],         time: ["medium","long"],   mode: ["discovery"],           future: false, emoji: "⚗", desc: "Understanding the composition and transformation of matter at the molecular level." },
  { id: 3,  name: "Physics",                 layer: "Matter",         domain: ["physical","symbolic"], target: ["matter","information"],  creation: ["knowledge"], abstraction: ["pure_theory"],  scale: ["cosmic"],         time: ["civilizational"],  mode: ["discovery"],           future: false, emoji: "⚛", desc: "Investigating the fundamental laws governing the universe, from quantum fields to spacetime." },
  { id: 4,  name: "Nanotechnology",          layer: "Matter",         domain: ["physical","digital"], target: ["matter","life"],  creation: ["technology","infrastructure"], abstraction: ["engineering"],  scale: ["global"],         time: ["long"],            mode: ["creation_m"],          future: true,  emoji: "◉", desc: "Engineering matter at nanoscale to create devices and systems with unprecedented capabilities." },
  { id: 5,  name: "Manufacturing",           layer: "Matter",         domain: ["physical"],       target: ["matter","civilization"],  creation: ["technology","infrastructure"], abstraction: ["operation","engineering"],  scale: ["global"],         time: ["short","medium"],  mode: ["optimization","creation_m"], future: false, emoji: "⚙", desc: "Designing and operating systems that transform raw materials into useful products at scale." },
  { id: 6,  name: "Mechanical Engineering",  layer: "Matter",         domain: ["physical"],       target: ["matter"],        creation: ["technology"],               abstraction: ["engineering"],               scale: ["organizational"], time: ["medium"],          mode: ["creation_m"],          future: false, emoji: "⚙", desc: "Designing machines, engines, and mechanical systems that interact with the physical world." },
  { id: 7,  name: "Electronics",             layer: "Matter/Digital", domain: ["physical","digital"], target: ["matter","information"],  creation: ["technology"],   abstraction: ["engineering"],  scale: ["global"],         time: ["medium"],          mode: ["creation_m"],          future: false, emoji: "⚡", desc: "Designing circuits and devices that control and process electrical signals." },
  { id: 8,  name: "Robotics",                layer: "Matter",         domain: ["physical","digital"], target: ["matter","society"],  creation: ["technology","systems"],   abstraction: ["engineering"],  scale: ["global"],         time: ["medium","long"],   mode: ["creation_m"],          future: true,  emoji: "⬟", desc: "Building autonomous machines that sense, decide, and act in the physical world." },
  { id: 9,  name: "Energy Systems",          layer: "Energy",         domain: ["physical"],       target: ["civilization"],  creation: ["infrastructure","systems"],  abstraction: ["engineering","operation"],    scale: ["planetary"],      time: ["long","civilizational"], mode: ["creation_m","optimization"], future: true,  emoji: "⚡", desc: "Engineering the systems that generate, store, and distribute energy across civilization." },
  { id: 10, name: "Mining",                  layer: "Matter",         domain: ["physical"],       target: ["matter"],        creation: ["infrastructure"],            abstraction: ["operation"],                 scale: ["national"],       time: ["short","medium"],  mode: ["exploration"],         future: false, emoji: "⬡", desc: "Extracting valuable minerals and resources from the Earth." },
  { id: 11, name: "Construction",            layer: "Infrastructure", domain: ["physical"],       target: ["civilization"],  creation: ["infrastructure"],            abstraction: ["operation","engineering"],    scale: ["local","national"], time: ["medium"],         mode: ["creation_m"],          future: false, emoji: "▣", desc: "Building the physical structures that form the backbone of civilization." },
  { id: 12, name: "Transportation Systems",  layer: "Infrastructure", domain: ["physical"],       target: ["civilization","society"],  creation: ["infrastructure","systems"],  abstraction: ["engineering"],  scale: ["global"],         time: ["long"],            mode: ["creation_m","optimization"], future: true,  emoji: "▷", desc: "Designing and operating systems that move people and goods across the world." },
  { id: 13, name: "Nuclear Engineering",     layer: "Energy",         domain: ["physical"],       target: ["civilization"],  creation: ["technology","infrastructure"], abstraction: ["engineering"],  scale: ["planetary"],      time: ["long","civilizational"], mode: ["creation_m"],  future: true,  emoji: "⚛", desc: "Harnessing nuclear reactions—fission or fusion—for clean, abundant energy." },
  { id: 14, name: "Aerospace Engineering",   layer: "Infrastructure", domain: ["physical"],       target: ["civilization"],  creation: ["technology","infrastructure"], abstraction: ["engineering"],  scale: ["cosmic"],         time: ["long","civilizational"], mode: ["creation_m","exploration"], future: true,  emoji: "◈", desc: "Designing aircraft, spacecraft, and systems that allow humanity to leave Earth." },
  { id: 15, name: "Ocean Engineering",       layer: "Infrastructure", domain: ["physical"],       target: ["matter","civilization"],  creation: ["technology","infrastructure"], abstraction: ["engineering"],  scale: ["global","planetary"], time: ["long"],   mode: ["exploration","creation_m"], future: false, emoji: "≋", desc: "Engineering structures, vehicles, and systems for the deep ocean environment." },
  { id: 16, name: "Fusion Research",         layer: "Energy",         domain: ["physical"],       target: ["civilization"],  creation: ["knowledge","technology"],   abstraction: ["pure_theory","engineering"],  scale: ["planetary"],      time: ["long","civilizational"], mode: ["discovery","creation_m"], future: true,  emoji: "⚡", desc: "Achieving controlled nuclear fusion to provide virtually unlimited clean energy." },
  { id: 17, name: "Advanced Materials",      layer: "Matter",         domain: ["physical"],       target: ["matter","civilization"],  creation: ["technology","knowledge"],   abstraction: ["engineering","pure_theory"],  scale: ["global"],         time: ["long"],            mode: ["discovery","creation_m"],  future: true,  emoji: "⬡", desc: "Creating room-temperature superconductors, metallic hydrogen, programmable matter." },

  // ── BIOLOGY / LIFE ────────────────────────
  { id: 20, name: "Genetics",                layer: "Life",           domain: ["physical","symbolic"], target: ["life"],      creation: ["knowledge","technology"],   abstraction: ["pure_theory","engineering"],  scale: ["global"],         time: ["long"],            mode: ["discovery"],           future: true,  emoji: "⬢", desc: "Studying and engineering the genetic code that defines living organisms." },
  { id: 21, name: "Biotechnology",           layer: "Life",           domain: ["physical","digital"], target: ["life","matter"],  creation: ["technology","systems"],   abstraction: ["engineering"],  scale: ["global"],         time: ["medium","long"],   mode: ["creation_m"],          future: true,  emoji: "⬢", desc: "Using living systems and organisms to develop products and processes." },
  { id: 22, name: "Medicine",                layer: "Life",           domain: ["physical","human_social"], target: ["life","mind"],  creation: ["knowledge","technology"], abstraction: ["engineering","operation"],  scale: ["personal","global"], time: ["immediate","medium"], mode: ["healing"],         future: false, emoji: "✿", desc: "Diagnosing, treating, and preventing disease to preserve and extend human life." },
  { id: 23, name: "Neuroscience",            layer: "Life/Mind",      domain: ["physical","symbolic"], target: ["life","mind","consciousness"],  creation: ["knowledge"],  abstraction: ["pure_theory"],  scale: ["global"],         time: ["long"],            mode: ["discovery"],           future: true,  emoji: "◉", desc: "Understanding the structure and function of the nervous system and brain." },
  { id: 24, name: "Agriculture",             layer: "Life",           domain: ["physical","human_social"], target: ["life","civilization"],  creation: ["systems","infrastructure"], abstraction: ["operation","engineering"],  scale: ["global"],         time: ["short","medium"],  mode: ["optimization"],        future: false, emoji: "⬢", desc: "Cultivating crops and raising livestock to feed civilization." },
  { id: 25, name: "Ecology",                 layer: "Life",           domain: ["physical"],       target: ["life","matter"],  creation: ["knowledge"],                abstraction: ["pure_theory"],               scale: ["planetary"],      time: ["long"],            mode: ["discovery"],           future: false, emoji: "⬢", desc: "Studying the relationships between organisms and their environments." },
  { id: 26, name: "Synthetic Biology",       layer: "Life",           domain: ["physical","digital"], target: ["life","matter"],  creation: ["technology","systems"],   abstraction: ["engineering","conceptual"],  scale: ["global"],         time: ["long","civilizational"], mode: ["creation_m","discovery"], future: true,  emoji: "⬢", desc: "Designing and engineering new biological parts, devices, and systems from scratch." },
  { id: 27, name: "Evolutionary Biology",    layer: "Life",           domain: ["physical","symbolic"], target: ["life"],      creation: ["knowledge"],                abstraction: ["pure_theory"],               scale: ["cosmic"],         time: ["civilizational"],  mode: ["discovery"],           future: false, emoji: "⬢", desc: "Studying the processes that drive biological diversity over evolutionary time." },
  { id: 28, name: "Longevity Research",      layer: "Life",           domain: ["physical","digital"], target: ["life","mind"],  creation: ["knowledge","technology"],   abstraction: ["engineering","pure_theory"],  scale: ["global"],         time: ["long","civilizational"], mode: ["discovery","healing"], future: true,  emoji: "◎", desc: "Understanding and reversing the mechanisms of aging to dramatically extend healthy lifespan." },
  { id: 29, name: "Nutrition Science",       layer: "Life",           domain: ["physical"],       target: ["life"],          creation: ["knowledge"],                abstraction: ["pure_theory","engineering"],  scale: ["personal","global"], time: ["medium"],          mode: ["discovery"],           future: false, emoji: "⬢", desc: "Understanding how food and nutrients affect human health and performance." },
  { id: 30, name: "Pharmacology",            layer: "Life",           domain: ["physical"],       target: ["life","mind"],   creation: ["knowledge","technology"],   abstraction: ["engineering"],               scale: ["global"],         time: ["medium"],          mode: ["discovery","healing"], future: false, emoji: "✿", desc: "Studying drug interactions with biological systems to develop effective treatments." },
  { id: 31, name: "Climate Engineering",     layer: "Environment",    domain: ["physical"],       target: ["matter","civilization"],  creation: ["systems","infrastructure"], abstraction: ["engineering","conceptual"],  scale: ["planetary"],      time: ["long","civilizational"], mode: ["creation_m"], future: true,  emoji: "◉", desc: "Deliberately intervening in Earth's climate systems to counteract global warming." },
  { id: 32, name: "Conservation Biology",    layer: "Environment",    domain: ["physical"],       target: ["life"],          creation: ["knowledge","systems"],      abstraction: ["conceptual","operation"],    scale: ["planetary"],      time: ["long"],            mode: ["healing"],             future: false, emoji: "⬢", desc: "Protecting biodiversity and restoring ecosystems at risk of collapse." },

  // ── DIGITAL / AI ──────────────────────────
  { id: 40, name: "Software Engineering",    layer: "Digital",        domain: ["digital"],        target: ["information"],   creation: ["technology","systems"],     abstraction: ["engineering"],               scale: ["global"],         time: ["short","medium"],  mode: ["creation_m"],          future: false, emoji: "⟨⟩", desc: "Designing, building, and maintaining software systems that power the digital world." },
  { id: 41, name: "Artificial Intelligence", layer: "Digital/Mind",   domain: ["digital","symbolic"], target: ["information","mind"],  creation: ["technology","systems","knowledge"], abstraction: ["conceptual","engineering"],  scale: ["global","planetary"], time: ["long","civilizational"], mode: ["creation_m","discovery"], future: true,  emoji: "◉", desc: "Engineering systems that can perceive, reason, learn, and act intelligently." },
  { id: 42, name: "Machine Learning",        layer: "Digital",        domain: ["digital"],        target: ["information"],   creation: ["technology","knowledge"],   abstraction: ["engineering","conceptual"],   scale: ["global"],         time: ["medium","long"],   mode: ["creation_m","discovery"], future: true,  emoji: "≋", desc: "Building systems that learn patterns from data to make predictions and decisions." },
  { id: 43, name: "Data Science",            layer: "Digital",        domain: ["digital"],        target: ["information","society"],  creation: ["knowledge","technology"],  abstraction: ["engineering"],  scale: ["organizational","global"], time: ["short","medium"], mode: ["discovery","optimization"], future: false, emoji: "≋", desc: "Extracting insights and value from large datasets using statistical and computational methods." },
  { id: 44, name: "Information Theory",      layer: "Digital/Symbolic", domain: ["digital","symbolic"], target: ["information"],  creation: ["knowledge"],  abstraction: ["pure_theory"],  scale: ["cosmic"],         time: ["civilizational"],  mode: ["discovery"],           future: false, emoji: "∞", desc: "The mathematical study of the quantification, storage, and communication of information." },
  { id: 45, name: "Cryptography",            layer: "Digital",        domain: ["digital","symbolic"], target: ["information","society"],  creation: ["knowledge","technology"],  abstraction: ["pure_theory","engineering"],  scale: ["global"],  time: ["long"],  mode: ["creation_m","discovery"], future: true,  emoji: "◈", desc: "Developing mathematical techniques to secure information and enable trustless communication." },
  { id: 46, name: "Distributed Systems",     layer: "Digital",        domain: ["digital"],        target: ["information","civilization"],  creation: ["technology","infrastructure"], abstraction: ["engineering"],  scale: ["global"],  time: ["medium"],  mode: ["creation_m"],          future: false, emoji: "⬡", desc: "Building systems that coordinate across many machines to provide reliability and scalability." },
  { id: 47, name: "Internet Infrastructure", layer: "Digital",        domain: ["digital"],        target: ["information","civilization"],  creation: ["infrastructure"],  abstraction: ["engineering","operation"],  scale: ["global","planetary"], time: ["medium","long"],  mode: ["creation_m","optimization"], future: false, emoji: "≋", desc: "Building and maintaining the physical and logical systems that form the global internet." },
  { id: 48, name: "Cybersecurity",           layer: "Digital",        domain: ["digital"],        target: ["information","society"],  creation: ["systems","knowledge"],  abstraction: ["engineering"],  scale: ["global"],  time: ["immediate","short"],  mode: ["discovery","optimization"], future: true,  emoji: "◈", desc: "Protecting digital systems, networks, and data from attacks and unauthorized access." },
  { id: 49, name: "Human-Computer Interaction", layer: "Digital",     domain: ["digital","human_social"], target: ["mind","information"],  creation: ["experiences","technology"],  abstraction: ["conceptual","engineering"],  scale: ["global"],  time: ["medium"],  mode: ["creation_m"],  future: false, emoji: "◎", desc: "Designing intuitive interfaces and interactions between humans and computer systems." },
  { id: 50, name: "AGI Research",            layer: "Digital/Mind",   domain: ["digital","symbolic"], target: ["information","mind","civilization"],  creation: ["knowledge","systems"],  abstraction: ["pure_theory","conceptual"],  scale: ["planetary","cosmic"], time: ["long","civilizational"],  mode: ["discovery","creation_m"], future: true,  emoji: "◉", desc: "Working toward artificial general intelligence—machines that can perform any cognitive task a human can." },
  { id: 51, name: "Blockchain Systems",      layer: "Digital",        domain: ["digital"],        target: ["information","society"],  creation: ["technology","institutions"],  abstraction: ["engineering"],  scale: ["global"],  time: ["medium","long"],  mode: ["creation_m"],  future: true,  emoji: "⬡", desc: "Decentralized ledger systems enabling trustless coordination and new economic models." },
  { id: 52, name: "Scientific AI",           layer: "Digital/Mind",   domain: ["digital","symbolic"], target: ["information","life","matter"],  creation: ["technology","knowledge"],  abstraction: ["engineering","conceptual"],  scale: ["global"],  time: ["long"],  mode: ["discovery","creation_m"], future: true,  emoji: "◉", desc: "AI systems specifically designed to accelerate scientific discovery (e.g. AlphaFold)." },
  { id: 53, name: "Autonomous Agents",       layer: "Digital",        domain: ["digital"],        target: ["information","society"],  creation: ["technology","systems"],  abstraction: ["engineering","conceptual"],  scale: ["global"],  time: ["medium","long"],  mode: ["creation_m"],  future: true,  emoji: "◉", desc: "Building AI systems that autonomously plan and execute multi-step goals in complex environments." },
  { id: 54, name: "Quantum Computing",       layer: "Digital",        domain: ["digital","symbolic","physical"], target: ["information","matter"],  creation: ["technology","knowledge"],  abstraction: ["engineering","pure_theory"],  scale: ["global"],  time: ["long"],  mode: ["discovery","creation_m"], future: true,  emoji: "⚛", desc: "Harnessing quantum mechanical phenomena to perform computations impossible for classical computers." },
  { id: 55, name: "Simulation Systems",      layer: "Digital",        domain: ["digital"],        target: ["information","society","civilization"],  creation: ["systems","technology"],  abstraction: ["engineering"],  scale: ["global","planetary"],  time: ["long"],  mode: ["creation_m"],  future: true,  emoji: "◎", desc: "Building massive digital-twin simulations of cities, economies, and physical systems for science and planning." },
  { id: 56, name: "Metaverse / VR Worlds",   layer: "Digital/Experiential", domain: ["digital","experiential"], target: ["mind","information","society"],  creation: ["experiences","systems"],  abstraction: ["conceptual","engineering"],  scale: ["global"],  time: ["medium","long"],  mode: ["creation_m"],  future: true,  emoji: "✦", desc: "Building persistent virtual worlds where people work, socialize, and create." },

  // ── HUMAN / SOCIAL ────────────────────────
  { id: 60, name: "Psychology",              layer: "Mind",           domain: ["human_social","symbolic"], target: ["mind"],  creation: ["knowledge"],  abstraction: ["pure_theory"],  scale: ["personal","organizational"],  time: ["medium"],  mode: ["discovery","healing"],  future: false, emoji: "◉", desc: "Studying human behavior, emotion, and cognition to understand the mind." },
  { id: 61, name: "Education",               layer: "Mind",           domain: ["human_social"],   target: ["mind","civilization"],  creation: ["experiences","systems","institutions"],  abstraction: ["conceptual"],  scale: ["local","global"],  time: ["medium","long"],  mode: ["teaching"],  future: false, emoji: "▷", desc: "Designing systems and practices that facilitate learning and development across the lifespan." },
  { id: 62, name: "Economics",               layer: "Social",         domain: ["human_social","symbolic"], target: ["society","civilization"],  creation: ["knowledge","institutions"],  abstraction: ["pure_theory","conceptual"],  scale: ["global","planetary"],  time: ["long"],  mode: ["discovery"],  future: false, emoji: "⬟", desc: "Studying the allocation of scarce resources and the behavior of markets and agents." },
  { id: 63, name: "Governance",              layer: "Social",         domain: ["human_social"],   target: ["society","civilization"],  creation: ["institutions","systems"],  abstraction: ["conceptual"],  scale: ["national","global"],  time: ["long","civilizational"],  mode: ["coordination"],  future: false, emoji: "⬟", desc: "Designing and operating the political and administrative systems that coordinate collective action." },
  { id: 64, name: "Law",                     layer: "Social",         domain: ["human_social","symbolic"], target: ["society"],  creation: ["institutions","knowledge"],  abstraction: ["conceptual"],  scale: ["national"],  time: ["medium","long"],  mode: ["coordination"],  future: false, emoji: "⬟", desc: "The system of rules that governs human behavior and resolves disputes in society." },
  { id: 65, name: "Organizational Design",   layer: "Social",         domain: ["human_social"],   target: ["society","civilization"],  creation: ["systems","institutions"],  abstraction: ["conceptual","operation"],  scale: ["organizational"],  time: ["medium"],  mode: ["creation_m","optimization"],  future: false, emoji: "⬡", desc: "Architecting the structures, processes, and culture of organizations for optimal performance." },
  { id: 66, name: "Public Policy",           layer: "Social",         domain: ["human_social"],   target: ["society","civilization"],  creation: ["institutions","systems"],  abstraction: ["conceptual","operation"],  scale: ["national","global"],  time: ["medium","long"],  mode: ["coordination"],  future: false, emoji: "⬟", desc: "Designing and implementing government policies that shape society and allocate public resources." },
  { id: 67, name: "Development Economics",   layer: "Social",         domain: ["human_social"],   target: ["society","civilization"],  creation: ["knowledge","institutions"],  abstraction: ["conceptual","pure_theory"],  scale: ["national","global"],  time: ["long"],  mode: ["discovery","coordination"],  future: false, emoji: "⬟", desc: "Understanding how poor countries can grow and improve living standards for their populations." },
  { id: 68, name: "Conflict Resolution",     layer: "Social",         domain: ["human_social"],   target: ["society"],  creation: ["knowledge","systems"],  abstraction: ["conceptual"],  scale: ["local","national"],  time: ["immediate","short"],  mode: ["healing","coordination"],  future: false, emoji: "◎", desc: "Mediating and resolving conflicts between individuals, groups, or nations." },
  { id: 69, name: "Diplomacy",               layer: "Social",         domain: ["human_social"],   target: ["civilization","society"],  creation: ["institutions"],  abstraction: ["operation"],  scale: ["global"],  time: ["medium"],  mode: ["coordination"],  future: false, emoji: "⬟", desc: "Managing relationships between nations to maintain peace and advance shared interests." },
  { id: 70, name: "Behavioral Science",      layer: "Mind",           domain: ["human_social","symbolic"], target: ["mind","society"],  creation: ["knowledge"],  abstraction: ["pure_theory"],  scale: ["global"],  time: ["medium"],  mode: ["discovery"],  future: false, emoji: "◉", desc: "Studying how cognitive biases and heuristics shape human decision-making and behavior." },
  { id: 71, name: "Cognitive Science",       layer: "Mind",           domain: ["human_social","symbolic","digital"], target: ["mind"],  creation: ["knowledge"],  abstraction: ["pure_theory","conceptual"],  scale: ["global"],  time: ["long"],  mode: ["discovery"],  future: true,  emoji: "◉", desc: "Interdisciplinary study of the mind and intelligent behavior using cognitive psychology, AI, and neuroscience." },
  { id: 72, name: "Intelligence Augmentation", layer: "Mind/Digital", domain: ["digital","human_social"], target: ["mind"],  creation: ["technology","experiences"],  abstraction: ["engineering","conceptual"],  scale: ["global","planetary"],  time: ["long"],  mode: ["creation_m"],  future: true,  emoji: "◉", desc: "Developing tools, interfaces, and systems that amplify human cognitive capabilities." },
  { id: 73, name: "Brain-Computer Interfaces", layer: "Mind/Digital", domain: ["physical","digital"], target: ["mind","life"],  creation: ["technology"],  abstraction: ["engineering"],  scale: ["global"],  time: ["long","civilizational"],  mode: ["creation_m"],  future: true,  emoji: "◉", desc: "Building direct communication pathways between the brain and external computing devices." },
  { id: 74, name: "Learning Science",        layer: "Mind",           domain: ["human_social","digital"], target: ["mind"],  creation: ["knowledge","experiences"],  abstraction: ["pure_theory","conceptual"],  scale: ["global"],  time: ["medium"],  mode: ["discovery","teaching"],  future: true,  emoji: "▷", desc: "Researching how humans learn most effectively to design better educational experiences." },

  // ── SYMBOLIC / ABSTRACT ───────────────────
  { id: 80, name: "Mathematics",             layer: "Symbolic",       domain: ["symbolic"],       target: ["information"],   creation: ["knowledge"],  abstraction: ["pure_theory"],  scale: ["cosmic"],  time: ["civilizational"],  mode: ["discovery"],  future: false, emoji: "∞", desc: "The queen of all sciences—discovering eternal truths about patterns, structure, and quantity." },
  { id: 81, name: "Philosophy",              layer: "Symbolic",       domain: ["symbolic"],       target: ["mind","consciousness","civilization"],  creation: ["knowledge"],  abstraction: ["pure_theory"],  scale: ["cosmic"],  time: ["civilizational"],  mode: ["discovery"],  future: false, emoji: "∞", desc: "Seeking ultimate understanding of existence, knowledge, values, and the nature of reality." },
  { id: 82, name: "Logic",                   layer: "Symbolic",       domain: ["symbolic"],       target: ["information"],   creation: ["knowledge"],  abstraction: ["pure_theory"],  scale: ["cosmic"],  time: ["civilizational"],  mode: ["discovery"],  future: false, emoji: "∞", desc: "Studying valid reasoning and inference—the foundations of mathematics and computer science." },
  { id: 83, name: "Theoretical Linguistics", layer: "Symbolic",       domain: ["symbolic","human_social"], target: ["mind","information"],  creation: ["knowledge"],  abstraction: ["pure_theory"],  scale: ["global"],  time: ["long"],  mode: ["discovery"],  future: false, emoji: "∞", desc: "Studying the structure, change, and universals of natural languages." },
  { id: 84, name: "Epistemology",            layer: "Symbolic",       domain: ["symbolic"],       target: ["mind","consciousness"],  creation: ["knowledge"],  abstraction: ["pure_theory"],  scale: ["cosmic"],  time: ["civilizational"],  mode: ["discovery"],  future: false, emoji: "∞", desc: "Investigating the nature, sources, and limits of human knowledge." },
  { id: 85, name: "Metaphysics",             layer: "Symbolic",       domain: ["symbolic"],       target: ["consciousness"],  creation: ["knowledge"],  abstraction: ["pure_theory"],  scale: ["cosmic"],  time: ["civilizational"],  mode: ["discovery"],  future: false, emoji: "∞", desc: "The deepest philosophical inquiry into the nature of being, existence, time, and reality." },
  { id: 86, name: "Philosophy of Mind",      layer: "Symbolic/Mind",  domain: ["symbolic","human_social"], target: ["mind","consciousness"],  creation: ["knowledge"],  abstraction: ["pure_theory"],  scale: ["cosmic"],  time: ["civilizational"],  mode: ["discovery"],  future: true,  emoji: "◉", desc: "Exploring the nature of consciousness, qualia, intentionality, and the mind-body problem." },
  { id: 87, name: "Philosophy of Science",   layer: "Symbolic",       domain: ["symbolic"],       target: ["information"],   creation: ["knowledge"],  abstraction: ["pure_theory"],  scale: ["cosmic"],  time: ["civilizational"],  mode: ["discovery"],  future: false, emoji: "∞", desc: "Examining the foundations, methods, and implications of science as a human enterprise." },
  { id: 88, name: "Ethics",                  layer: "Symbolic",       domain: ["symbolic"],       target: ["society","consciousness"],  creation: ["knowledge","institutions"],  abstraction: ["pure_theory","conceptual"],  scale: ["global","cosmic"],  time: ["civilizational"],  mode: ["discovery"],  future: true,  emoji: "∞", desc: "Investigating the foundations of morality and developing frameworks for evaluating right action." },
  { id: 89, name: "Political Philosophy",    layer: "Symbolic",       domain: ["symbolic","human_social"], target: ["society","civilization"],  creation: ["knowledge","institutions"],  abstraction: ["pure_theory"],  scale: ["global"],  time: ["civilizational"],  mode: ["discovery"],  future: false, emoji: "∞", desc: "Reasoning about justice, rights, authority, and ideal forms of social organization." },

  // ── EXPERIENTIAL / CREATIVE ───────────────
  { id: 100, name: "Visual Art",             layer: "Culture",        domain: ["experiential"],   target: ["mind","society","consciousness"],  creation: ["experiences","stories_culture"],  abstraction: ["conceptual","pure_theory"],  scale: ["personal","global"],  time: ["medium"],  mode: ["creation_m"],  future: false, emoji: "✦", desc: "Creating visual works that evoke emotion, challenge perception, and reflect the human condition." },
  { id: 101, name: "Music",                  layer: "Culture",        domain: ["experiential"],   target: ["mind","consciousness"],  creation: ["experiences","stories_culture"],  abstraction: ["conceptual"],  scale: ["global"],  time: ["medium"],  mode: ["creation_m"],  future: false, emoji: "♪", desc: "Composing and performing organized sound to communicate emotion and create beauty." },
  { id: 102, name: "Cinema / Film",          layer: "Culture",        domain: ["experiential"],   target: ["mind","society","consciousness"],  creation: ["experiences","stories_culture"],  abstraction: ["conceptual"],  scale: ["global"],  time: ["medium"],  mode: ["creation_m"],  future: false, emoji: "✦", desc: "Creating moving image narratives that explore the human experience at scale." },
  { id: 103, name: "Literature",             layer: "Culture",        domain: ["experiential"],   target: ["mind","society","consciousness"],  creation: ["stories_culture","knowledge"],  abstraction: ["conceptual","pure_theory"],  scale: ["global"],  time: ["medium","long"],  mode: ["creation_m"],  future: false, emoji: "✦", desc: "Writing novels, poetry, and prose that illuminate the depths of human experience." },
  { id: 104, name: "Video Games",            layer: "Experiential",   domain: ["experiential","digital"], target: ["mind","society"],  creation: ["experiences","systems"],  abstraction: ["engineering","conceptual"],  scale: ["global"],  time: ["medium"],  mode: ["creation_m"],  future: true,  emoji: "✦", desc: "Designing interactive experiences that combine play, narrative, and mechanics into transformative systems." },
  { id: 105, name: "Mythology & Narrative",  layer: "Culture",        domain: ["experiential","human_social"], target: ["mind","society","civilization"],  creation: ["stories_culture","knowledge"],  abstraction: ["conceptual","pure_theory"],  scale: ["global"],  time: ["civilizational"],  mode: ["creation_m","discovery"],  future: false, emoji: "✦", desc: "Creating and studying the foundational stories that give civilizations their meaning and identity." },
  { id: 106, name: "Immersive Storytelling", layer: "Experiential",   domain: ["experiential","digital"], target: ["mind","consciousness"],  creation: ["experiences","stories_culture"],  abstraction: ["conceptual","engineering"],  scale: ["global"],  time: ["medium","long"],  mode: ["creation_m"],  future: true,  emoji: "✦", desc: "AR/VR narrative experiences that place the audience inside the story." },
  { id: 107, name: "Architecture",           layer: "Infrastructure", domain: ["physical","experiential"], target: ["matter","mind","civilization"],  creation: ["infrastructure","experiences"],  abstraction: ["conceptual"],  scale: ["local","national"],  time: ["long"],  mode: ["creation_m"],  future: false, emoji: "▣", desc: "Designing built environments that shape how humans inhabit and experience the world." },
  { id: 108, name: "Animation",              layer: "Culture",        domain: ["experiential","digital"], target: ["mind","society"],  creation: ["experiences","stories_culture"],  abstraction: ["conceptual"],  scale: ["global"],  time: ["medium"],  mode: ["creation_m"],  future: false, emoji: "✦", desc: "Bringing characters and worlds to life through sequential images in service of story." },
  { id: 109, name: "World Building",         layer: "Experiential",   domain: ["experiential","symbolic"], target: ["mind","consciousness","civilization"],  creation: ["experiences","stories_culture","systems"],  abstraction: ["pure_theory","conceptual"],  scale: ["global","cosmic"],  time: ["civilizational"],  mode: ["creation_m"],  future: true,  emoji: "✦", desc: "Constructing entire fictional universes with internally consistent geography, history, culture, and metaphysics." },
  { id: 110, name: "Cultural Preservation",  layer: "Culture",        domain: ["experiential","human_social"], target: ["society","civilization"],  creation: ["stories_culture","knowledge"],  abstraction: ["operation"],  scale: ["national"],  time: ["civilizational"],  mode: ["healing"],  future: false, emoji: "◈", desc: "Documenting and safeguarding the languages, traditions, and artifacts of human cultures." },
  { id: 111, name: "Media Ecosystems",       layer: "Culture",        domain: ["human_social","digital"], target: ["mind","society"],  creation: ["systems","stories_culture"],  abstraction: ["conceptual","engineering"],  scale: ["global"],  time: ["medium"],  mode: ["creation_m"],  future: true,  emoji: "≋", desc: "Building platforms and systems that distribute stories, news, and culture at global scale." },
  { id: 112, name: "Theatre & Performance",  layer: "Culture",        domain: ["experiential"],   target: ["mind","consciousness"],  creation: ["experiences","stories_culture"],  abstraction: ["conceptual"],  scale: ["local","national"],  time: ["immediate"],  mode: ["creation_m"],  future: false, emoji: "✦", desc: "The live performance of drama, movement, and voice to create transformative experiences." },
  { id: 113, name: "Game Design Theory",     layer: "Experiential",   domain: ["symbolic","experiential"], target: ["mind","information"],  creation: ["knowledge","experiences"],  abstraction: ["conceptual","pure_theory"],  scale: ["global"],  time: ["long"],  mode: ["discovery","creation_m"],  future: true,  emoji: "✦", desc: "The systematic study of player psychology, feedback loops, and the principles of engagement." },

  // ── CONSCIOUSNESS / INNER ─────────────────
  { id: 120, name: "Meditation Traditions",  layer: "Consciousness",  domain: ["experiential","symbolic"], target: ["consciousness","mind"],  creation: ["experiences","knowledge"],  abstraction: ["pure_theory","operation"],  scale: ["personal"],  time: ["civilizational"],  mode: ["exploration","discovery"],  future: false, emoji: "◎", desc: "Contemplative practices developed across traditions to train attention and explore the nature of awareness." },
  { id: 121, name: "Consciousness Studies",  layer: "Consciousness",  domain: ["symbolic","physical","human_social"], target: ["consciousness","mind"],  creation: ["knowledge"],  abstraction: ["pure_theory"],  scale: ["cosmic"],  time: ["civilizational"],  mode: ["discovery"],  future: true,  emoji: "◎", desc: "The scientific study of subjective experience, qualia, and the hard problem of consciousness." },
  { id: 122, name: "Psychedelic Research",   layer: "Consciousness",  domain: ["physical","symbolic"], target: ["consciousness","mind","life"],  creation: ["knowledge"],  abstraction: ["pure_theory","engineering"],  scale: ["global"],  time: ["long"],  mode: ["discovery"],  future: true,  emoji: "◎", desc: "Investigating how psychoactive compounds affect conscious experience and their therapeutic potential." },
  { id: 123, name: "Contemplative Philosophy", layer: "Consciousness", domain: ["symbolic"],       target: ["consciousness","mind"],  creation: ["knowledge"],  abstraction: ["pure_theory"],  scale: ["cosmic"],  time: ["civilizational"],  mode: ["discovery","exploration"],  future: false, emoji: "∞", desc: "Philosophical traditions centred on deep inquiry into the nature of the self and reality." },
  { id: 124, name: "Spiritual Systems",      layer: "Consciousness",  domain: ["experiential","symbolic"], target: ["consciousness"],  creation: ["experiences","institutions","stories_culture"],  abstraction: ["conceptual"],  scale: ["global"],  time: ["civilizational"],  mode: ["exploration"],  future: false, emoji: "◎", desc: "Comprehensive systems of practice, belief, and community oriented toward ultimate meaning and liberation." },

  // ── CIVILIZATION INFRASTRUCTURE ───────────
  { id: 130, name: "Urban Planning",         layer: "Infrastructure", domain: ["physical","human_social"], target: ["civilization","society"],  creation: ["infrastructure","systems","experiences"],  abstraction: ["conceptual"],  scale: ["local","national"],  time: ["long"],  mode: ["creation_m"],  future: false, emoji: "▣", desc: "Designing cities that balance density, movement, housing, green space, and human flourishing." },
  { id: 131, name: "Space Infrastructure",   layer: "Infrastructure", domain: ["physical"],       target: ["civilization"],  creation: ["infrastructure","technology"],  abstraction: ["engineering"],  scale: ["cosmic"],  time: ["civilizational"],  mode: ["creation_m","exploration"],  future: true,  emoji: "◈", desc: "Building the launch systems, orbital platforms, lunar bases, and interplanetary habitats for spacefaring civilization." },
  { id: 132, name: "Supply Chain / Logistics", layer: "Infrastructure", domain: ["physical","digital"], target: ["civilization"],  creation: ["systems","infrastructure"],  abstraction: ["operation","engineering"],  scale: ["global"],  time: ["short","medium"],  mode: ["optimization","coordination"],  future: false, emoji: "▷", desc: "Coordinating the global flow of goods, materials, and food from production to consumption." },
  { id: 133, name: "Water Systems",          layer: "Infrastructure", domain: ["physical"],       target: ["civilization","life"],  creation: ["infrastructure"],  abstraction: ["operation","engineering"],  scale: ["national","global"],  time: ["long"],  mode: ["creation_m","maintenance"],  future: false, emoji: "≋", desc: "Engineering systems for water treatment, distribution, and management for human and ecological needs." },
  { id: 134, name: "Satellite Constellations", layer: "Infrastructure", domain: ["physical","digital"], target: ["civilization","information"],  creation: ["infrastructure","technology"],  abstraction: ["engineering"],  scale: ["planetary"],  time: ["long"],  mode: ["creation_m"],  future: true,  emoji: "◈", desc: "Networks of satellites in low-Earth orbit providing global internet and remote sensing coverage." },
  { id: 135, name: "Global Knowledge Systems", layer: "Digital",       domain: ["digital","human_social"], target: ["information","civilization"],  creation: ["systems","knowledge","infrastructure"],  abstraction: ["conceptual","engineering"],  scale: ["global"],  time: ["long","civilizational"],  mode: ["creation_m","coordination"],  future: true,  emoji: "≋", desc: "Platforms that organize, connect, and make accessible the entirety of human knowledge." },
  { id: 136, name: "Civilization Governance", layer: "Social",        domain: ["human_social","digital"], target: ["civilization","society"],  creation: ["systems","institutions"],  abstraction: ["conceptual"],  scale: ["global","planetary"],  time: ["civilizational"],  mode: ["coordination","creation_m"],  future: true,  emoji: "⬟", desc: "Designing new systems for coordinating billions of people across nations on shared challenges." },

  // ── FUTURE HORIZONS (extra) ───────────────
  { id: 140, name: "Terraforming",           layer: "Planetary",      domain: ["physical"],       target: ["matter","civilization"],  creation: ["systems","infrastructure"],  abstraction: ["conceptual","engineering"],  scale: ["cosmic"],  time: ["civilizational"],  mode: ["creation_m"],  future: true,  emoji: "◉", desc: "Deliberately transforming the climate and environment of another planet to support human life." },
  { id: 141, name: "Digital Twins",          layer: "Digital",        domain: ["digital","physical"], target: ["information","civilization"],  creation: ["systems","technology"],  abstraction: ["engineering"],  scale: ["global"],  time: ["medium","long"],  mode: ["creation_m"],  future: true,  emoji: "≋", desc: "Real-time digital replicas of physical systems—cities, factories, bodies—used for simulation and optimization." },
  { id: 142, name: "Cybernetics",            layer: "Digital/Physical", domain: ["physical","digital"], target: ["life","mind","information"],  creation: ["knowledge","technology"],  abstraction: ["pure_theory","engineering"],  scale: ["global"],  time: ["long"],  mode: ["discovery","creation_m"],  future: false, emoji: "⬡", desc: "The study of regulatory systems and feedback loops in machines and living organisms." },
  { id: 143, name: "Design/UX",              layer: "Digital/Experiential", domain: ["experiential","digital","human_social"], target: ["mind","society"],  creation: ["experiences"],  abstraction: ["conceptual"],  scale: ["global"],  time: ["short","medium"],  mode: ["creation_m"],  future: false, emoji: "✦", desc: "Creating interfaces and products that are useful, usable, and delightful to human beings." },
  { id: 144, name: "Education Reinvention",  layer: "Mind",           domain: ["digital","human_social"], target: ["mind","civilization"],  creation: ["systems","experiences","institutions"],  abstraction: ["conceptual"],  scale: ["global"],  time: ["long","civilizational"],  mode: ["creation_m","teaching"],  future: true,  emoji: "▷", desc: "Rebuilding education from first principles using AI personalization, intrinsic motivation, and mastery learning." },
  { id: 145, name: "Astrobiology",           layer: "Life",           domain: ["physical","symbolic"], target: ["life","matter"],  creation: ["knowledge"],  abstraction: ["pure_theory"],  scale: ["cosmic"],  time: ["civilizational"],  mode: ["discovery","exploration"],  future: true,  emoji: "⬢", desc: "Investigating the origin, evolution, and possibility of life throughout the universe." },
  { id: 146, name: "Deep Sea Exploration",   layer: "Environment",    domain: ["physical"],       target: ["life","matter"],  creation: ["knowledge"],  abstraction: ["operation","pure_theory"],  scale: ["planetary"],  time: ["long"],  mode: ["exploration","discovery"],  future: false, emoji: "≋", desc: "Mapping and studying the ecosystems, geology, and potential resources of the deep ocean." },
  { id: 147, name: "Complexity Science",     layer: "Symbolic",       domain: ["symbolic","physical","digital"], target: ["information"],  creation: ["knowledge"],  abstraction: ["pure_theory","conceptual"],  scale: ["cosmic"],  time: ["civilizational"],  mode: ["discovery"],  future: true,  emoji: "∞", desc: "Studying emergent phenomena in complex adaptive systems—from economies to ecosystems to brains." },
  { id: 148, name: "Interstellar Mission Design", layer: "Infrastructure", domain: ["physical"],  target: ["civilization"],  creation: ["knowledge","infrastructure"],  abstraction: ["conceptual","pure_theory"],  scale: ["cosmic"],  time: ["civilizational"],  mode: ["creation_m","exploration"],  future: true,  emoji: "◈", desc: "Designing the propulsion, life support, and communications for missions to other star systems." },
  { id: 149, name: "AI Safety",              layer: "Digital/Mind",   domain: ["digital","symbolic"], target: ["civilization","mind"],  creation: ["knowledge","systems"],  abstraction: ["pure_theory","conceptual"],  scale: ["planetary","cosmic"],  time: ["long","civilizational"],  mode: ["discovery"],  future: true,  emoji: "◉", desc: "Ensuring that increasingly powerful AI systems remain aligned with human values and beneficial to civilization." },
  { id: 150, name: "Cognitive Enhancement",  layer: "Mind",           domain: ["human_social","digital","physical"], target: ["mind"],  creation: ["technology"],  abstraction: ["engineering"],  scale: ["global"],  time: ["long"],  mode: ["creation_m","healing"],  future: true,  emoji: "◉", desc: "Developing pharmacological, technology, and training interventions that expand human cognition and perception." },
];

// ─────────────────────────────────────────────
//  ARCHETYPES
// ─────────────────────────────────────────────
const ARCHETYPES = [
  { id: "discoverer",    name: "The Discoverer",    icon: "◎", desc: "Seeks truth about reality", color: "#a78bfa", examples: "Einstein, Newton", domains: [3,80,81,82,84,85,25,27], drive: "What is the true nature of the universe?" },
  { id: "inventor",      name: "The Inventor",      icon: "⚙", desc: "Creates new tools & tech",   color: "#60a5fa", examples: "Tesla, Edison",   domains: [6,7,8,13,14,16,17,54],   drive: "What new capability can humanity gain?" },
  { id: "system_builder",name: "The System Builder", icon: "⬡", desc: "Creates complex systems",   color: "#34d399", examples: "Musk, Bezos",    domains: [40,41,46,47,65,132,133,9], drive: "How can large systems be designed to work?" },
  { id: "explorer",      name: "The Explorer",       icon: "◈", desc: "Pushes into unknown territories", color: "#fb923c", examples: "Cousteau, Gagarin", domains: [131,145,146,148,10,15,12], drive: "What lies beyond the known?" },
  { id: "philosopher",   name: "The Philosopher",    icon: "∞", desc: "Seeks ultimate wisdom",     color: "#e879f9", examples: "Socrates, Laozi", domains: [81,82,84,85,86,87,88,89,123], drive: "What is the deepest truth of existence?" },
  { id: "story_creator", name: "The Story Creator",  icon: "✦", desc: "Shapes myths & imagination", color: "#f472b6", examples: "Disney, Miyazaki", domains: [100,101,102,103,104,105,108,109,110], drive: "What worlds can be imagined?" },
  { id: "exp_designer",  name: "Experience Designer", icon: "✿", desc: "Creates powerful experiences", color: "#fbbf24", examples: "Miyamoto",    domains: [104,106,56,112,113,143,49,107], drive: "What can humans feel and experience?" },
  { id: "civ_architect", name: "Civilization Architect", icon: "⬟", desc: "Shapes society & structures", color: "#2dd4bf", examples: "Lee Kuan Yew", domains: [63,64,66,130,131,135,136,67], drive: "How should society be organized?" },
  { id: "intel_creator", name: "Intelligence Creator", icon: "◉", desc: "Builds thinking systems",  color: "#818cf8", examples: "Hinton, Hassabis", domains: [41,42,50,52,53,54,71,72,73,149], drive: "Can intelligence itself be engineered?" },
  { id: "synthesizer",   name: "Knowledge Synthesizer", icon: "⬢", desc: "Connects many domains",   color: "#a3e635", examples: "Da Vinci",     domains: [71,147,87,42,74,70,81,83,84], drive: "How does everything connect?" },
  { id: "consciousness_exp", name: "Consciousness Explorer", icon: "✿", desc: "Investigates awareness", color: "#fb7185", examples: "Buddha",    domains: [120,121,122,123,124,86,81,60], drive: "What is consciousness itself?" },
  { id: "world_builder", name: "The World Builder",   icon: "✦", desc: "Creates entire universes",  color: "#facc15", examples: "Tolkien, Lucas", domains: [109,104,105,106,56,103,108,101], drive: "What entire worlds can be created?" },
];

// ─────────────────────────────────────────────
//  FUTURE TOP-20 FIELDS
// ─────────────────────────────────────────────
const FUTURE_FIELDS_IDS = [41,42,26,28,8,9,131,56,55,52,51,17,135,109,121,136,144,73,134,140];
